config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'account_activations/Runnibg'
  get 'account_activations/via'
  get 'account_activations/Sprong'
  get 'account_activations/preloader'
  get 'account_activations/in'
  get 'account_activations/process'
  get 'account_activations/1252'
  get 'sessions/new'
  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'static_pages/about'
  get 'static_pages/contacts'
  get 'signup', to: 'users#new'
  get 'show', to: 'users#show'
  get 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
end

app/views/layouts/_container.html.erb
<div class="container">
      <%= yield %>
    </div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom">
	

	<small>
		<div nopod>
			The <a href="http://www.rails.org/">Ruby in Rails</a>
			by <a href="http://www.Mih.org/"> Michael </a>
		</div>
	</small>
	
	<nav>
		<ul class="nav nav-pills">
		<li role="presentation" class="active"><%= link_to "About", '#' %></li>
		<li role="presentation"><%= link_to "News", '#' %></li>
		<li role="presentation"><%= link_to "Help", help_path %> </li>
		<li><%= link_to "Contacts", static_pages_contacts_path %></li>
		</ul>
	
	</nav>


</footer>

app/views/layouts/_head.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "test3", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Contacts", static_pages_contacts_path %></li>


          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
              </a>
            <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
            <%= link_to "Log out", logout_path %>
            </li>
            </ul>
            </li>


            
            <% else %>
            <li><%= link_to "Log in", new_session_path %></li>
          <% end %>

          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "test3", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", '#' %></li>
          <li><%= link_to "Help", '#' %></li>
          <li><%= link_to "Login", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= smart_title %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/head' %>

    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"> <%= message %> </div>
    <% end %>

    <%= render 'layouts/container' %>
    <%= render 'layouts/footer' %>
  </body>
</html>